name: "Ung Vetenskapssport"
permalink: "/blog/:year/:month/:day/:title/"
timezone: "Europe/Stockholm"
encoding: "utf-8"
discordLink: "https://discord.gg/GDfJKkTaqb"
facebookLink: "https://www.facebook.com/ungvetenskapssport"
instagramLink: "https://www.instagram.com/ungvetenskapssport/"
