name: "Ung Vetenskapssport"
permalink: "/blog/:year/:month/:day/:title/"
timezone: "Europe/Stockholm"
encoding: "utf-8"
discordLink: "https://discord.gg/T89S8XzwrG"
facebookLink: "https://www.facebook.com/ungvetenskapssport"
